package portal

import (
	"bytes"
	"embed"
	"encoding/xml"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"
	"time"
)

//go:embed templates/*
var defaultTemplates embed.FS

// ErrSafetyOverwrite indicates that an existing index.html lacks a RepoView signature.
type ErrSafetyOverwrite struct {
	Path string
}

func (e *ErrSafetyOverwrite) Error() string {
	return fmt.Sprintf("safety violation: %s already exists and was not generated by RepoView (use --force to overwrite)", e.Path)
}

// Renderer compiles catalog HTML and aggregated RSS feeds.
type Renderer struct {
	tmpl *template.Template
}

// NewRenderer initializes a new portal Renderer with embedded or custom templates.
func NewRenderer(customTemplateDir string) (*Renderer, error) {
	funcMap := template.FuncMap{
		"upper": func(v interface{}) string {
			return strings.ToUpper(fmt.Sprint(v))
		},
		"lower": func(v interface{}) string {
			return strings.ToLower(fmt.Sprint(v))
		},
	}

	var t *template.Template
	if customTemplateDir != "" {
		pattern := filepath.Join(customTemplateDir, "*.html")
		var err error
		t, err = template.New("").Funcs(funcMap).ParseGlob(pattern)
		if err != nil {
			return nil, fmt.Errorf("failed to parse custom templates: %w", err)
		}
	} else {
		var err error
		t, err = template.New("").Funcs(funcMap).ParseFS(defaultTemplates, "templates/*.html")
		if err != nil {
			return nil, fmt.Errorf("failed to parse embedded portal templates: %w", err)
		}
	}

	return &Renderer{tmpl: t}, nil
}

// PortalContext passes state to portal.html.
type PortalContext struct {
	Catalog *Catalog
}

// RenderHTML executes portal.html template and returns HTML bytes.
func (r *Renderer) RenderHTML(catalog *Catalog) ([]byte, error) {
	if catalog == nil {
		return nil, fmt.Errorf("catalog cannot be nil")
	}

	var buf bytes.Buffer
	ctx := PortalContext{Catalog: catalog}

	if err := r.tmpl.ExecuteTemplate(&buf, "portal.html", ctx); err != nil {
		return nil, fmt.Errorf("failed to execute portal template: %w", err)
	}

	return buf.Bytes(), nil
}

// RSS XML Models for Aggregated Feed (Option C)

type rssFeed struct {
	XMLName xml.Name   `xml:"rss"`
	Version string     `xml:"version,attr"`
	Channel rssChannel `xml:"channel"`
}

type rssChannel struct {
	Title         string    `xml:"title"`
	Link          string    `xml:"link"`
	Description   string    `xml:"description"`
	Language      string    `xml:"language"`
	LastBuildDate string    `xml:"lastBuildDate"`
	Generator     string    `xml:"generator"`
	Items         []rssItem `xml:"item"`
}

type rssItem struct {
	Title       string `xml:"title"`
	Link        string `xml:"link"`
	Description string `xml:"description"`
	PubDate     string `xml:"pubDate"`
	GUID        string `xml:"guid"`
	date        time.Time
}

// RenderFeed compiles an aggregated RSS 2.0 feed merging latest child feeds and repository updates.
func (r *Renderer) RenderFeed(catalog *Catalog, rootDir string) ([]byte, error) {
	if catalog == nil {
		return nil, fmt.Errorf("catalog cannot be nil")
	}

	var allItems []rssItem
	now := time.Now().UTC()

	// 1. Collect repository update cards
	for _, repo := range catalog.Repos {
		targetLink := repo.TargetURL
		if catalog.BaseURL != "" && !strings.HasPrefix(targetLink, "http://") && !strings.HasPrefix(targetLink, "https://") {
			targetLink = strings.TrimSuffix(catalog.BaseURL, "/") + "/" + strings.TrimPrefix(targetLink, "/")
		}

		buildTime := repo.LastBuild
		if buildTime.IsZero() {
			buildTime = now
		}

		item := rssItem{
			Title:       fmt.Sprintf("[%s] %s (%s)", strings.ToUpper(repo.Distro), repo.Title, repo.Arch),
			Link:        targetLink,
			Description: fmt.Sprintf("Repository updated with %d packages. Format: %s, Channel/Components: %s", repo.PackageCount, strings.ToUpper(string(repo.Format)), repo.Channel),
			PubDate:     buildTime.Format(time.RFC1123Z),
			GUID:        targetLink + "#" + buildTime.Format("20060102150405"),
			date:        buildTime,
		}
		allItems = append(allItems, item)
	}

	// 2. Option C: Parallel aggregation of latest items from child repo latest-feed.xml
	if rootDir != "" {
		var candidateRepos []*DiscoveredRepo
		for _, repo := range catalog.Repos {
			if repo.IsRendered && repo.Path != "" {
				candidateRepos = append(candidateRepos, repo)
			}
		}

		if len(candidateRepos) > 0 {
			numWorkers := runtime.NumCPU() * 2
			if numWorkers < 1 {
				numWorkers = 1
			}
			if numWorkers > len(candidateRepos) {
				numWorkers = len(candidateRepos)
			}

			repoChan := make(chan *DiscoveredRepo, len(candidateRepos))
			for _, r := range candidateRepos {
				repoChan <- r
			}
			close(repoChan)

			resChan := make(chan []rssItem, len(candidateRepos))
			var wg sync.WaitGroup

			for w := 0; w < numWorkers; w++ {
				wg.Add(1)
				go func() {
					defer wg.Done()
					var localItems []rssItem
					for repo := range repoChan {
						items := r.readChildFeedItems(repo, rootDir, catalog.BaseURL)
						localItems = append(localItems, items...)
					}
					resChan <- localItems
				}()
			}
			wg.Wait()
			close(resChan)

			for items := range resChan {
				allItems = append(allItems, items...)
			}
		}
	}

	// Sort items descending by publication date
	sort.Slice(allItems, func(i, j int) bool {
		return allItems[i].date.After(allItems[j].date)
	})

	// Limit to top 50 entries
	if len(allItems) > 50 {
		allItems = allItems[:50]
	}

	channelLink := catalog.BaseURL
	if channelLink == "" {
		channelLink = "index.html"
	}

	feed := rssFeed{
		Version: "2.0",
		Channel: rssChannel{
			Title:         catalog.Title + " - Unified Feed",
			Link:          channelLink,
			Description:   catalog.Description,
			Language:      "en-us",
			LastBuildDate: now.Format(time.RFC1123Z),
			Generator:     "RepoView-Portal",
			Items:         allItems,
		},
	}

	var buf bytes.Buffer
	buf.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
	enc := xml.NewEncoder(&buf)
	enc.Indent("", "  ")
	if err := enc.Encode(feed); err != nil {
		return nil, fmt.Errorf("failed to encode RSS XML: %w", err)
	}

	return buf.Bytes(), nil
}

// readChildFeedItems extracts up to 5 latest items from a child repo's latest-feed.xml.
func (r *Renderer) readChildFeedItems(repo *DiscoveredRepo, rootDir, portalBaseURL string) []rssItem {
	candidates := []string{
		filepath.Join(repo.Path, "repoview", "latest-feed.xml"),
		filepath.Join(repo.Path, "latest-feed.xml"),
	}

	var feedPath string
	for _, c := range candidates {
		if fi, err := os.Stat(c); err == nil && !fi.IsDir() {
			feedPath = c
			break
		}
	}

	if feedPath == "" {
		return nil
	}

	// #nosec G304 -- reading discovered child feed
	data, err := os.ReadFile(filepath.Clean(feedPath))
	if err != nil {
		return nil
	}

	var parsed rssFeed
	if err := xml.Unmarshal(data, &parsed); err != nil {
		return nil
	}

	var items []rssItem
	limit := 5
	for i, it := range parsed.Channel.Items {
		if i >= limit {
			break
		}

		t, err := time.Parse(time.RFC1123Z, it.PubDate)
		if err != nil {
			t, err = time.Parse(time.RFC1123, it.PubDate)
			if err != nil {
				t = time.Now().UTC()
			}
		}

		itemLink := it.Link
		if !strings.HasPrefix(itemLink, "http://") && !strings.HasPrefix(itemLink, "https://") {
			// Resolve relative link from repo directory
			repoRel := repo.RelPath
			if strings.Contains(repo.TargetURL, "/repoview/") {
				repoRel = filepath.ToSlash(filepath.Join(repoRel, "repoview"))
			}
			itemLink = filepath.ToSlash(filepath.Join(repoRel, itemLink))
			if portalBaseURL != "" {
				itemLink = strings.TrimSuffix(portalBaseURL, "/") + "/" + strings.TrimPrefix(itemLink, "/")
			}
		}

		items = append(items, rssItem{
			Title:       fmt.Sprintf("[%s] %s", repo.Title, it.Title),
			Link:        itemLink,
			Description: it.Description,
			PubDate:     t.Format(time.RFC1123Z),
			GUID:        it.GUID,
			date:        t,
		})
	}

	return items
}

// WritePortal outputs index.html and portal-feed.xml into outputDir with overwrite safety and atomic rename.
func (r *Renderer) WritePortal(outputDir, rootDir string, catalog *Catalog, force bool) error {
	if catalog == nil {
		return fmt.Errorf("catalog cannot be nil")
	}

	cleanOut := filepath.Clean(outputDir)
	// #nosec G301 -- static web portal directories require standard permissions (0755) for web server access
	if err := os.MkdirAll(cleanOut, 0o755); err != nil {
		return fmt.Errorf("failed to create output directory %s: %w", cleanOut, err)
	}

	indexPath := filepath.Join(cleanOut, "index.html")

	// Overwrite Safety Guard (Option 2)
	if fi, err := os.Stat(indexPath); err == nil && !fi.IsDir() {
		if !force {
			// #nosec G304 -- inspecting pre-existing file for signature
			data, err := os.ReadFile(indexPath)
			if err == nil {
				content := string(data)
				if !strings.Contains(content, "RepoView-Portal") && !strings.Contains(content, `name="generator" content="RepoView"`) {
					return &ErrSafetyOverwrite{Path: indexPath}
				}
			}
		}
	}

	// Adjust relative target URLs if portal outputDir is different from rootDir
	absOut, errOut := filepath.Abs(cleanOut)
	absRoot, errRoot := filepath.Abs(rootDir)
	if errOut == nil && errRoot == nil && absOut != absRoot {
		for _, repo := range catalog.Repos {
			if repo.IsExternal || strings.HasPrefix(repo.TargetURL, "http://") || strings.HasPrefix(repo.TargetURL, "https://") {
				continue
			}
			absTarget := filepath.Join(absRoot, repo.TargetURL)
			if rel, err := filepath.Rel(absOut, absTarget); err == nil {
				repo.TargetURL = filepath.ToSlash(rel)
			}
		}
	}

	// Render HTML
	htmlBytes, err := r.RenderHTML(catalog)
	if err != nil {
		return err
	}

	if err := atomicWriteFile(indexPath, htmlBytes); err != nil {
		return fmt.Errorf("failed to write index.html: %w", err)
	}

	// Render Feed
	feedBytes, err := r.RenderFeed(catalog, rootDir)
	if err != nil {
		return err
	}

	feedPath := filepath.Join(cleanOut, "portal-feed.xml")
	if err := atomicWriteFile(feedPath, feedBytes); err != nil {
		return fmt.Errorf("failed to write portal-feed.xml: %w", err)
	}

	return nil
}

// atomicWriteFile writes data to an ephemeral temporary file and atomically renames it.
func atomicWriteFile(destPath string, data []byte) error {
	dir := filepath.Dir(destPath)
	tmpFile, err := os.CreateTemp(dir, filepath.Base(destPath)+".*.tmp")
	if err != nil {
		return err
	}
	tmpPath := tmpFile.Name()
	defer func() {
		_ = os.Remove(tmpPath)
	}()

	if _, err := tmpFile.Write(data); err != nil {
		_ = tmpFile.Close()
		return err
	}
	if err := tmpFile.Sync(); err != nil {
		_ = tmpFile.Close()
		return err
	}
	if err := tmpFile.Close(); err != nil {
		return err
	}

	// #nosec G302 -- static web portal assets require standard web server readability (0644)
	if err := os.Chmod(tmpPath, 0o644); err != nil {
		return err
	}

	return os.Rename(tmpPath, destPath)
}
